name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-diamond:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install pipenv
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - run: pipenv requirements > requirements.txt
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - run: docker build diamond -f diamond/Dockerfile -t us-central1-docker.pkg.dev/genomic-nlp/cloudrun/diamond
      - run: docker push us-central1-docker.pkg.dev/genomic-nlp/cloudrun/diamond:latest
      - run: gcloud builds submit --quiet --tag us-central1-docker.pkg.dev/genomic-nlp/cloudrun/diamond:latest
  # TODO: update running instance and remove old images.
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install pipenv
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - run: pipenv requirements > requirements.txt
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - run: docker build server -f server/Dockerfile -t us-central1-docker.pkg.dev/genomic-nlp/cloudrun/gnlp-server
      - run: docker push us-central1-docker.pkg.dev/genomic-nlp/cloudrun/gnlp-server:latest
      - run: gcloud builds submit --quiet --tag us-central1-docker.pkg.dev/genomic-nlp/cloudrun/gnlp-server:latest

  # create-public-assets:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: google-github-actions/auth@v0
  #       with:
  #         credentials_json: ${{ secrets.GCP_CREDENTIALS }}
  #     - uses: google-github-actions/setup-gcloud@v0
  #     - uses: actions/setup-python@v3
  #       with:
  #         python-version: "3.10"
  #     - run: python -m pip install --upgrade pip
  #     - run: python -m pip install pipenv
  #     - uses: actions/cache@v3
  #       with:
  #         path: ~/.local/share/virtualenvs
  #         key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
  #     - run: pipenv install --deploy
  #     - run: gsutil cp gs://gnlp-public-assets/data/model_data.pkl model_data.pkl
  #     - run: pipenv run python server/scripts/plot.py --data model_data.pkl --outdir=web/src/assets/map --fmt png --max-zoom 5
  #     - run: gsutil -m rsync web/src/assets/map gs://gnlp-public-assets/map
