name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-diamond:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install pipenv
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - run: gsutil cp gs://gnlp.bursteinlab.org/data/diamond/words.dmnd diamond/
      - run: docker build diamond -t us-central1-docker.pkg.dev/genomic-nlp/cloudrun/diamond
      - run: docker push us-central1-docker.pkg.dev/genomic-nlp/cloudrun/diamond:latest
      - run: gcloud run deploy diamond --image=us-central1-docker.pkg.dev/genomic-nlp/cloudrun/diamond:latest --region us-central1
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install pipenv
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - run: pipenv requirements > server/requirements.txt
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - run: gsutil cp gs://gnlp.bursteinlab.org/data/model_data.pkl server/
      - run: gsutil cp gs://gnlp.bursteinlab.org/data/gene_names_to_ko.pkl server/
      - run: gsutil cp gs://gnlp.bursteinlab.org/data/label_to_word.pkl server/
      - run: docker build server -t us-central1-docker.pkg.dev/genomic-nlp/cloudrun/gnlp-server
      - run: docker push us-central1-docker.pkg.dev/genomic-nlp/cloudrun/gnlp-server:latest
      - run: gcloud run deploy gnlp-server --image=us-central1-docker.pkg.dev/genomic-nlp/cloudrun/gnlp-server:latest --region us-central1

  cleanup-artifact-registry:
    runs-on: ubuntu-latest
    needs: [deploy-diamond, deploy-server]
    steps:
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v0
      # Delete all but the latest image
      - run: gcloud artifacts --project genomic-nlp docker images list --include-tags us-central1-docker.pkg.dev/genomic-nlp/cloudrun | awk '$3 ~ !/^latest$/' | awk '{print $1"@"$2}' | xargs -L1 gcloud artifacts docker images delete --async --delete-tags --quiet

  create-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install pipenv
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - run: pipenv install --dev
      - run: gsutil cp gs://gnlp.bursteinlab.org/data/model_data.pkl ./
      - run: pipenv run python server/plot.py --outdir=web/src/assets/map --fmt png --max-zoom 7
      - run: gsutil -m rsync -rd web/src/assets/map gs://gnlp.bursteinlab.org/map

  create-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: web/yarn.lock
      - run: yarn --cwd web install
      - run: yarn --cwd web vite build
      - run: gsutil cp web/dist/index.html gs://gnlp.bursteinlab.org/index.html
      - run: gsutil -m rsync -rd web/dist/assets gs://gnlp.bursteinlab.org/assets
