name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prettify code
      uses: creyD/prettier_action@v4.2
      with:
        dry: True