name: CI

on:
  push:
    branches:
      - main

jobs:
  build-env:
    runs-on: ubuntu-latest
    - uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/gnlp:latest