name: Map

on:
  workflow_dispatch:

jobs:
  create-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install pipenv
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - run: pipenv install --dev
      - run: gsutil cp gs://gnlp.bursteinlab.org/data/model_data.pkl ./
      - run: pipenv run python server/plot.py --outdir=web/src/assets/map --fmt png --max-zoom 7
      - run: gsutil -m rsync -rd web/src/assets/map gs://gnlp.bursteinlab.org/map
