name: Map

on:
  workflow_dispatch:
    inputs:
      min_zoom:
        description: "Min zoom level for map tiles"
        default: 0
      max_png_zoom:
        description: "Max zoom level for PNG tiles"
        default: 8
      max_zoom:
        description: "Max zoom level for map tiles"
        default: 9
      min_img_points:
        description: "Min number of points for image tiles"
        default: 250

jobs:
  create-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install pipenv
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - run: pipenv install --dev
      - run: gsutil cp gs://gnlp.bursteinlab.org/data/model_data.pkl ./
      - run: pipenv run python server/plot.py --outdir=web/public/map --min-zoom ${{ github.event.inputs.min_zoom }} --max-png-zoom ${{ github.event.inputs.max_png_zoom }} --max-zoom ${{ github.event.inputs.max_zoom }} --min-img-points ${{ github.event.inputs.min_img_points }}
      - run: gsutil -m rsync -rd web/public/map gs://gnlp.bursteinlab.org/map
